name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '20 5 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'run bot'
        run: python bot.py
